version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: shared_db
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

  main:
    build:
      context: ./main
    depends_on:
      - database
    environment:
      - MONGO_URL=mongodb://shared_db:27017/testTask
      - PORT=8080

  dashboard:
    build:
      context: ./dashboard
    depends_on:
      - database
    environment:
      - MONGO_URL=mongodb://shared_db:27017/testTask
      - PORT=8081

volumes:
  db_data:
